import enum


class UserRole(str, enum.Enum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    INVESTIGATING_OFFICER = "INVESTIGATING_OFFICER"
    FORENSIC_OFFICER = "FORENSIC_OFFICER"
    COURT_OFFICER = "COURT_OFFICER"
    LEGAL_OFFICER = "LEGAL_OFFICER"
    AUDITOR = "AUDITOR"
    READ_ONLY_REVIEWER = "READ_ONLY_REVIEWER"


class CaseStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    SUSPENDED = "SUSPENDED"


class CasePriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DocumentType(str, enum.Enum):
    FIR = "FIR"
    POLICE_REPORT = "POLICE_REPORT"
    INVESTIGATION_REPORT = "INVESTIGATION_REPORT"
    WITNESS_STATEMENT = "WITNESS_STATEMENT"
    CHARGE_SHEET = "CHARGE_SHEET"
    COURT_FILING = "COURT_FILING"
    EVIDENCE_RECORD = "EVIDENCE_RECORD"
    FORENSIC_REPORT = "FORENSIC_REPORT"
    LEGAL_NOTICE = "LEGAL_NOTICE"
    JUDGMENT = "JUDGMENT"
    OTHER = "OTHER"


class Classification(str, enum.Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    HIGHLY_CONFIDENTIAL = "HIGHLY_CONFIDENTIAL"
    SEALED = "SEALED"


class IntegrityStatus(str, enum.Enum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    FAILED = "FAILED"


class CustodyStatus(str, enum.Enum):
    WITH_INVESTIGATOR = "WITH_INVESTIGATOR"
    WITH_FORENSICS = "WITH_FORENSICS"
    IN_TRANSIT = "IN_TRANSIT"
    WITH_COURT = "WITH_COURT"
    SEALED = "SEALED"
    ARCHIVED = "ARCHIVED"


class DocumentStatus(str, enum.Enum):
    QUARANTINED = "QUARANTINED"
    VALIDATING = "VALIDATING"
    HASHING = "HASHING"
    EXTRACTING = "EXTRACTING"
    AI_ANALYSIS = "AI_ANALYSIS"
    CREATING_EVIDENCE_DNA = "CREATING_EVIDENCE_DNA"
    SEALING = "SEALING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class AccessPurpose(str, enum.Enum):
    INVESTIGATION = "INVESTIGATION"
    COURT_PREPARATION = "COURT_PREPARATION"
    FORENSIC_ANALYSIS = "FORENSIC_ANALYSIS"
    ADMINISTRATIVE_REVIEW = "ADMINISTRATIVE_REVIEW"
    EVIDENCE_VERIFICATION = "EVIDENCE_VERIFICATION"


class AccessAction(str, enum.Enum):
    VIEW = "VIEW"
    DOWNLOAD = "DOWNLOAD"
    SHARE = "SHARE"


class AccessRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DENIED = "DENIED"


class AlertSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"


class NotificationSeverity(str, enum.Enum):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
