import { AccessPurpose, UserRole } from "@/types";

/**
 * UI-only mirror of the backend permission matrix (app/security/rbac.py) — kept in exact
 * sync with it. This controls which nav items, tabs, and action buttons are shown so a role
 * never sees a control it cannot actually use; it is NOT a security boundary. The backend
 * independently re-checks every permission on every request regardless of what the UI shows.
 */
export const PERMISSIONS = {
  CASE_CREATE: "CASE_CREATE",
  CASE_VIEW: "CASE_VIEW",
  CASE_UPDATE: "CASE_UPDATE",
  DOCUMENT_UPLOAD: "DOCUMENT_UPLOAD",
  DOCUMENT_VIEW: "DOCUMENT_VIEW",
  DOCUMENT_DOWNLOAD: "DOCUMENT_DOWNLOAD",
  EVIDENCE_VIEW: "EVIDENCE_VIEW",
  EVIDENCE_VERIFY: "EVIDENCE_VERIFY",
  EVIDENCE_TRANSFER: "EVIDENCE_TRANSFER",
  CUSTODY_VIEW: "CUSTODY_VIEW",
  AUDIT_VIEW: "AUDIT_VIEW",
  SECURITY_VIEW: "SECURITY_VIEW",
  SECURITY_RESOLVE: "SECURITY_RESOLVE",
  ACCESS_REQUEST_CREATE: "ACCESS_REQUEST_CREATE",
  ACCESS_REQUEST_APPROVE: "ACCESS_REQUEST_APPROVE",
  AI_USE: "AI_USE",
  COURT_VERIFY: "COURT_VERIFY",
  CERTIFICATE_GENERATE: "CERTIFICATE_GENERATE",
  USER_MANAGE: "USER_MANAGE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
} as const;

type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Mirrors ROLE_PERMISSIONS in app/security/rbac.py exactly — update both together.
const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SYSTEM_ADMIN: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_RESOLVE,
    PERMISSIONS.ACCESS_REQUEST_APPROVE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.DOCUMENT_VIEW,
  ],
  INVESTIGATING_OFFICER: [
    PERMISSIONS.CASE_CREATE,
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.CASE_UPDATE,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.CUSTODY_VIEW,
    PERMISSIONS.ACCESS_REQUEST_CREATE,
    PERMISSIONS.AI_USE,
  ],
  FORENSIC_OFFICER: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_VERIFY,
    PERMISSIONS.EVIDENCE_TRANSFER,
    PERMISSIONS.CUSTODY_VIEW,
    PERMISSIONS.ACCESS_REQUEST_CREATE,
    PERMISSIONS.AI_USE,
  ],
  COURT_OFFICER: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_VERIFY,
    PERMISSIONS.CUSTODY_VIEW,
    PERMISSIONS.COURT_VERIFY,
    PERMISSIONS.CERTIFICATE_GENERATE,
    PERMISSIONS.ACCESS_REQUEST_CREATE,
  ],
  LEGAL_OFFICER: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_DOWNLOAD,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.CUSTODY_VIEW,
    PERMISSIONS.ACCESS_REQUEST_CREATE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.COURT_VERIFY,
  ],
  AUDITOR: [
    PERMISSIONS.CASE_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.CUSTODY_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
  ],
  READ_ONLY_REVIEWER: [PERMISSIONS.CASE_VIEW, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.EVIDENCE_VIEW],
};

export function can(role: UserRole | undefined, permission: Permission): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

// Mirrors ROLE_ALLOWED_PURPOSES in app/security/rbac.py. A role's document actions must be
// requested with a purpose it's actually allowed to use — e.g. Forensic Officer can't use
// "INVESTIGATION", only FORENSIC_ANALYSIS / EVIDENCE_VERIFICATION — or the backend's ABAC
// decision denies the request purely on purpose, independent of role/case/classification.
const DEFAULT_PURPOSE: Record<UserRole, AccessPurpose> = {
  SYSTEM_ADMIN: "ADMINISTRATIVE_REVIEW",
  INVESTIGATING_OFFICER: "INVESTIGATION",
  FORENSIC_OFFICER: "FORENSIC_ANALYSIS",
  COURT_OFFICER: "COURT_PREPARATION",
  LEGAL_OFFICER: "COURT_PREPARATION",
  AUDITOR: "ADMINISTRATIVE_REVIEW",
  READ_ONLY_REVIEWER: "ADMINISTRATIVE_REVIEW",
};

export function defaultPurposeForRole(role: UserRole | undefined): AccessPurpose {
  return role ? DEFAULT_PURPOSE[role] : "ADMINISTRATIVE_REVIEW";
}
